### ISSUE TITLE
how to fix it

### ISSUE THREAD

**Issue by saaya009** [nekocode/Emojix#2]
-  Process: com.robb.fg, PID: 18357
-                                                              java.lang.IllegalStateException: A factory has already been set on this LayoutInflater
-                                                                  at android.view.LayoutInflater.setFactory2(LayoutInflater.java:308)
-                                                                  at cn.nekocode.emojix.EmojixLayoutInflater.setFactory2(EmojixLayoutInflater.java:85)
-                                                                  at android.support.v4.view.LayoutInflaterCompatLollipop.setFactory(LayoutInflaterCompatLollipop.java:24)
-                                                                  at android.support.v4.view.LayoutInflaterCompat$LayoutInflaterCompatImplV21.setFactory(LayoutInflaterCompat.java:55)
-                                                                  at android.support.v4.view.LayoutInflaterCompat.setFactory(LayoutInflaterCompat.java:85)
-                                                                  at android.support.v4.app.Fragment.getLayoutInflater(Fragment.java:1118)
-                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
-                                                                  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
-                                                                  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
-                                                                  at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1632)
-                                                                  at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:637)
-                                                                  at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
-                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1235)
-                                                                  at android.support.v4.view.ViewPager.populate(ViewPager.java:1083)
-                                                                  at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1609)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:900)
-                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
-                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
-                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
-                                                                  at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
-                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
-                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
-                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
-                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
-                                                                  at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1467)
-                                                                  at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
-                                                                  at android.widget.LinearLayout.onMeasure(LinearLayout.java:638)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5548)
-                                                                  at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
-                                                                  at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2636)
-                                                                  at android.view.View.measure(View.java:17621)
-                                                                  at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2081)
-                                                                  at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1217)
-                                                                  at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1423)
-                                                                  at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1105)
-                                                                  at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6204)
-                                                                  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:799)
-                                                                  at android.view.Choreographer.doCallbacks(Choreographer.java:612)
-                                                                  at android.view.Choreographer.doFrame(Choreographer.java:581)
-                                                                  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:785)
-                                                                  at android.os.Handler.handleCallback(Handler.java:739)
-                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
-                                                                  at android.os.Looper.loop(Looper.java:135)
-                                                               at android.app.ActivityThread.main(
- 07-29 17:39:01.864 872-893/? E/ReportTools: This is not beta user build
- 07-29 17:39:01.944 872-3467/? E/InputDispatcher: channel '90cdec5 com.robb.fg/com.robb.fg.activity.home.IndexActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
- 07-29 17:39:01.974 872-4080/? E/HsmCoreServiceImpl: onTransact in code is: 102
- 07-29 17:39:02.034 13286-17326/? E/HAL: hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8909.so
- 07-29 17:39:02.144 289-289/? E/HAL: hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8909.so
- 07-29 17:39:02.194 289-289/? E/HAL: hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8909.so
- 07-29 17:39:02.524 872-4142/? E/HsmCoreServiceImpl: onTransact in code is: 102
- 07-29 17:39:02.654 18645-18645/? E/hisync.STUtils: java.lang.IllegalArgumentException: input.length=0; inputOffset=16; inputLen=-16
-                                                        at javax.crypto.Cipher.checkInputOffsetAndCount(Cipher.java:1038)
-                                                        at javax.crypto.Cipher.doFinal(Cipher.java:1374)
-                                                        at com.huawei.android.hicloud.util.a.a(Aes128Cbc.java:264)
-                                                        at com.huawei.android.hicloud.util.a.b(Aes128Cbc.java:131)
-                                                        at com.huawei.android.hicloud.util.z.c(STUtils.java:105)
-                                                        at com.huawei.android.hicloud.common.account.a.b(AccountInfo.java:203)
-                                                        at com.huawei.android.hicloud.common.account.a.a(AccountInfo.java:158)
-                                                        at com.huawei.android.hicloud.HicloudApplication.onCreate(HicloudApplication.java:70)
-                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
-                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4850)
-                                                        at android.app.ActivityThread.access$1900(ActivityThread.java:165)
-                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
-                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
-                                                        at android.os.Looper.loop(Looper.java:135)
-                                                        at android.app.ActivityThread.main(ActivityThread.java:5593)
-                                                        at java.lang.reflect.Method.invoke(Native Method)
-                                                        at java.lang.reflect.Method.invoke(Method.java:372)
-                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
-                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)
- 07-29 17:39:02.654 18645-18645/? E/hisync.STUtils: java.lang.IllegalArgumentException: input.length=0; inputOffset=16; inputLen=-16
-                                                        at javax.crypto.Cipher.checkInputOffsetAndCount(Cipher.java:1038)
-                                                        at javax.crypto.Cipher.doFinal(Cipher.java:1374)
-                                                        at com.huawei.android.hicloud.util.a.a(Aes128Cbc.java:264)
-                                                        at com.huawei.android.hicloud.util.a.b(Aes128Cbc.java:131)
-                                                        at com.huawei.android.hicloud.util.z.c(STUtils.java:105)
-                                                        at com.huawei.android.hicloud.common.account.a.b(AccountInfo.java:204)
-                                                        at com.huawei.android.hicloud.common.account.a.a(AccountInfo.java:158)
-                                                        at com.huawei.android.hicloud.HicloudApplication.onCreate(HicloudApplication.java:70)
-                                                        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
-                                                        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4850)
-                                                        at android.app.ActivityThread.access$1900(ActivityThread.java:165)
-                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1442)
-                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
-                                                        at android.os.Looper.loop(Looper.java:135)
-                                                        at android.app.ActivityThread.main(ActivityThread.java:5593)
-                                                        at java.lang.reflect.Method.invoke(Native Method)
-                                                        at java.lang.reflect.Method.invoke(Method.java:372)
-                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:967)
-                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by nekocode** [comment]
Can you provide more detailed information about it, such as source code and your android version.

**Comment by daidaijie** [comment]
I have the same question too
My android version is 5.0.2
defaultConfig {
        applicationId "com.example.daidaijie.syllabusapplication"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }

**Comment by nekocode** [comment]
@saaya009 @daidaijie  Yep, I have found the reason. I will fix it tonight. Thank you for yours information.

**Comment by nekocode** [comment]
@saaya009 @daidaijie Hey, guys. I have tried to fix this issue in the **[new version 1.1](https://github.com/nekocode/Emojix/releases/tag/1.1)**. Please have a try and give me feedback, thanks!

**Comment by daidaijie** [comment]
@nekocode OK，but all of my TextView default textcolor become dark

**Comment by nekocode** [comment]
@daidaijie  It's so strange. Im sorry about that I can't reproduce it. I will keep this issue open until it is fixed.

**Comment by daidaijie** [comment]
@nekocode ok,Thank you for sharing this codes

**Comment by saaya009** [comment]
@nekocode  I use HUAWEI 5.1.1 the emoji didn't become apple style,they was  google style

**Comment by nekocode** [comment]
@saaya009 Please try the [Calligraphy](https://github.com/chrisjenx/Calligraphy) library and give me a feedback that is this library running well on your device. Thanks.

**Comment by fly7632785** [comment]
I just wanna know which latest version is ?

**Comment by nekocode** [comment]
@fly7632785 The lastest version is `1.1` now. You can get it through the 'Jitpack' badge in the README's header.

**Comment by fly7632785** [comment]
谢谢，我还想问一下。如果可以把emoji的图库使用暴露出来，然后我们弄个emoji键盘就好了。不然，只能用解析，不能用的话有点可惜

**Comment by nekocode** [comment]
@fly7632785  你弄个键盘里面都是 TextView，然后填充 Emoji 字符进去就行了。再或者你也可以直接使用 ImageView 引用库里面的 Emoji 图片资源：[https://github.com/nekocode/Emojix/tree/master/lib-emojix/src/main/res/drawable-nodpi](https://github.com/nekocode/Emojix/tree/master/lib-emojix/src/main/res/drawable-nodpi)
