### ISSUE TITLE
can't sync 

### ISSUE THREAD

**Issue by daidaijie** [nekocode/Emojix#3]
Error:Could not find com.github.nekocode:Emojix:{lastest-version}.
Required by:
    SyllabusApplication:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by nekocode** [comment]
@daidaijie Hey guy, please replace the `{lastest-version}` to the library lastest version name manually by yourself. Such as:

```
compile 'com.github.nekocode:Emojix:1.0'
```

**Comment by daidaijie** [comment]
thanks
