### ISSUE TITLE
1.2.0  no find!!!

### ISSUE THREAD

**Issue by geogie** [nekocode/Emojix#6]
Error:Could not find com.github.nekocode:Emojix:{1.2.0}.
Required by:
    CloudClassroom_Android:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by geogie** [comment]
Error:Could not find com.github.nekocode:Emojix:{lastest-version}.
Required by:
    CloudClassroom_Android:app:unspecified
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by brotoo25** [comment]
Same here!

**Comment by nekocode** [comment]
@geogie  @brotoo25  The jitpack build has broken,... Please try again, I have already made a rebuilding.

```
dependencies {
    compile 'com.github.nekocode:Emojix:1.2'
}
```
