### ISSUE TITLE
关于资源体积问题

### ISSUE THREAD

**Issue by daidaijie** [nekocode/Emojix#7]
请问资源文件夹下的emoji可以使用tingpng优化下大小吗

**Comment by nekocode** [comment]
再压缩的话可能会失真了，你可以尝试一下。

**Comment by daidaijie** [comment]
@nekocode 那请问之前你有进行过压缩吗

**Comment by nekocode** [comment]
资源来自于 [emojicon](https://github.com/rockerhieu/emojicon)，我并没有做任何处理。

**Comment by daidaijie** [comment]
@nekocode 好的，谢谢解答
