### ISSUE TITLE
关于版本的问题

### ISSUE THREAD

**Issue by farsunset** [nekocode/Emojix#9]
最新版本是多少
lastest-version填什么？
dependencies {
    compile 'com.github.nekocode:Emojix:{lastest-version}'
}

**Comment by nekocode** [comment]
Check the jitpack badge: 
![image](https://user-images.githubusercontent.com/4783781/34251927-a866c46c-e67c-11e7-81ef-be908d990d0a.png)

**Comment by farsunset** [comment]
好的谢谢你，emoji图片会跟随ios不断更新吗

**Comment by nekocode** [comment]
No, it will not. Check here: https://github.com/nekocode/Emojix/blob/master/lib-emojix/src/main/res/drawable-nodpi
Becase it uses static images to display emoji characters.
